config/routes.rb
BlogApp::Application.routes.draw do
  resources :posts do
    member do
      get 'like'
    end
    resources :comments
  end
  match ':controller/:action/:id'
  match ':controller(/:action(/:id))(.:format)'
  root :to => 'posts#index'
  match "signup", :to => "users#new"
  match "login", :to => "sessions#login"
  match "logout", :to => "sessions#logout"
end

app/models/post.rb
class Post < ActiveRecord::Base
  make_flaggable :like
	has_many :comments, dependent: :destroy, :as => :commentable
  attr_accessor :photo, :search
	attr_accessible :title, :body ,:photo
	belongs_to :user
	validates :title, :presence => true, :uniqueness => true
	validates :body, :presence => true, :uniqueness => true
  has_attached_file :photo, :styles => {
  	:small  => "150x150>"},
    :url => "/assets/images/:id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/images/:id/:style/:basename.:extension"
    validates_attachment_content_type :photo, :content_type => ['image/jpeg','image/png','image/jpg','image/bmp']
  
  def self.search(search)
    if search
     where("title LIKE ? OR body LIKE ?","%#{search.strip}%","%#{search.strip}%")
    else
      scoped
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user, :except => [:index, :show ]
  
  def like
    @post = Post.includes(:comments).find(params[:id])
    @loggedin_user = User.find(session[:user_id])
    if @loggedin_user.flagged?(@post, :like)
      @loggedin_user.unflag!(@post,:like)
      msg = "You now dont like this Post"
    else
      @loggedin_user.flag!(@post,:like)
      msg = "You now like this Post"
      @count = nil
      @count = @post.flaggings.count
      Rails.logger.debug("***************************************")
      puts @count # stores number of likes of a particular post
      Rails.logger.debug("***************************************")
    end
    redirect_to post_url, :notice => msg
  end

  def index
    @posts = Post.includes(:comments).search(params[:search]).paginate(per_page:2, page: params[:page]).order("created_at DESC")
  end

  def show
    @post = Post.includes(:comments).find(params[:id])
    @comments = @post.comments
    @totalcomments = @post.comments.count.to_i
    @loggedin_user = user_def
    @count = @post.flaggings.count
  end

  def new
    @post = Post.new
  end

  def edit
    @post = user_def.posts.find(params[:id])
    unless @post.user == user_def
      flash[:notice] = 'You are not authorized to Edit this Post.'
      flash[:color] = 'invalid'
      redirect_to posts_path
    end
  end

  def create
    @post = user_def.posts.new(params[:post])
    unless @post.user == user_def
      flash[:notice] = 'You are not authorized to Create the Post.'
      flash[:color] = 'invalid'
      redirect_to login_path
    end
    if @post.save
      redirect_to @post, :notice => "#{@post.title}, is successfully created."
      flash[:notice]
    else
      render 'new'
    end
  end

  def update  
    @post = user_def.posts.find(params[:id])
    unless @post.user == user_def
      flash[:notice] = 'You are not authorized to Update this Post.'
      flash[:color] = 'invalid'
      redirect_to login_path
    end
    if @post.update_attributes(params[:post])
        redirect_to @post, :notice => "#{@post.title}, is successfully updated." 
        flash[:notice]
    else
      render 'edit'
    end
  end

  def destroy
    @post = user_def.posts.find(params[:id])
    unless @post.user == user_def
      flash[:notice] = 'You are not authorized to Delete the Post.'
      flash[:color] = "invalid"
      redirect_to login_path    
		end
      redirect_to posts_path, :notice=> "#{@post.title}, is successfully deleted."
      flash[:notice]	  
			@post.destroy    
  end
end

app/helpers/posts_helper.rb
module PostsHelper
	def toggle_like_button(post,loggedin_user)
		if @loggedin_user.flagged?(@post, :like)
			#link_to "Unlike", like_post_path(@post)
			link_to "Unlike", like_post_path(@post)
		else
			#link_to "Like", like_post_path(@post)
			link_to "Like", like_post_path(@post)
		end

	end	
end

app/views/posts/_form.html.erb
<%= form_for @post, :html => {:multipart => true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
<h2><%= pluralize(@post.errors.count, "error")%>prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>
<%= render 'form' %>
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1 class='User_Header'><center>Blog Posts</center></h1>
<div class = "notice">
  <%= flash[:notice] %>
</div>
<div class = "search">
  <span class ="search"> 
    <%= form_tag(posts_path, :method => :get) do %>
    <%= text_field_tag (:search), params[:search] %>
    <%= submit_tag 'Search' %>
      <% if @posts.empty? %>
  </br>
</br>
<p>
  No Post Matches to search criteria, 
</p>
<p>
  Please try using different Keywords
</p>
      <% end %>
    <% end %>
  </span>
</div>
<br/>
</br>
<table>
<% @posts.each do |post| %>
  <tr>
    <td>
      <b>
        <strong>
          <u>
            <h2>
              <%= link_to post.title, post_path(post) %>
            </h2>
          </u>
        </strong>
      </b>
    </td>
  </tr>
  <tr>
    <td>
      <%= truncate(post.body, :length => 250) %>
    </td>
  </tr>
  <tr>
    <td>
      <b>
        <small>
          <span class="timestamp">
            Posted <%= time_ago_in_words(post.created_at) %> ago.
          </span>
          <span class ="author">
            &nbsp;by -&nbsp;<%= post.user.username %>
          </span>
        </small>
      </b>
    </br>
  </br>
</br>
<% if post.user == user_def  %>
  <%= link_to 'Edit this Post', edit_post_path(post) %>      
  | <%= link_to 'Delete this Post', post, method: :delete, 
  data: { confirm: 'Are you sure, you want to delete this Post ?' } %>
</td>
<% end %>
</tr>
<% end %>
</table>
<%= will_paginate @posts %>
</br>
</br>
<% if user_def %>
  <%= link_to 'Create a new Post', new_post_path %>
</br>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= render 'form' %>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"></p>
<p>
</br>
</br>
</br>
<h2><%= @post.title %></h2>
</p>
</br>
<b>
  <small>
    <span class="timestamp">
      Posted <%= time_ago_in_words(@post.created_at) %> ago.
    </span>
    <span class ="author">
     &nbsp;by -&nbsp;<%= @post.user.username %>
    </span>
  </small>
</b>
</br>
</br>
<p>
	<%= @post.body %>
</p>
<% if @post.photo.present? %>
<p>
	<%= image_tag(@post.photo.url(:small)) %>
</p>
<% end %>
</br>
</br>
</br>
<%= link_to 'Back', posts_path %>
<%= link_to 'Add a Comment', new_post_comment_path(@post) %>
<br/>
<% if @post.user == user_def  %>
  <%= link_to 'Edit this Post', edit_post_path(@post) %>      
  | <%= link_to 'Delete this Post', @post, method: :delete, data: { confirm: 'Are you sure, you want to delete this post ?' } %>
<% end %>
<% if user_def %>
| <%= toggle_like_button(@post,@loggedin_user) %>
( <%= @count %> )
<% end %>
</br>
</br>
<% title = "Comments"%></br><u><b>Comments : </b></u>( <%= @totalcomments %> )
<div id="comments">
	<% for comment in @comments %>
</br>
<small>
  @&nbsp;<b><u><%=link_to comment.name, post_comment_path(@post,comment) %></u></b>&nbsp;says,
  <i>
    <%=simple_format comment.body%>
  </i>
  <% if @post.user==user_def %>     
    <%= link_to 'Delete this Comment', post_comment_url(@post, comment), method: :delete, data: { confirm: 'Are you sure, you want to delete this comment ?' } %>
  <% end %>
  <b>
    <span class="timestamp">
      Posted <%= time_ago_in_words(comment.created_at) %> ago.
    </span>
  </b>
</small>
</br>
<% end %>
</div>